MAIN_O=main.o
OTHER_O=mybank.o
C=gcc -g

all:final

final:$(MAIN_O) libmyBank.so
    $(C) $(MAIN_O) ./libmyBank.so -o $@
libmyBank.so=$(OTHER_O)
    $(C) -shared $^ -o $@

MAIN_O=main.c mybank.h 
    $(C) -c main.c
OTHER_O= mybank.c mybank.h
    $(C) -c mybank.c

    .PHONY:clean all
    
    clean:
    rm *.o *.so final